[[d1_databases]]
binding = "DB"
database_name = "snapurl-db"
database_id = "0bde5f6f-1d88-4eec-bc7f-1ea67bbcccce"  # From creation output

[vars]
FRONTEND_URL = "http://localhost:3000"
SERVICE_API_KEY = "su_dev_bootstrap_key"